# Site settings
title: Lucas Bradstreet
email: lucasbradstreet@gmail.com
description: Musings on programming, functional programming, and distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lbradstreet.github.io" # the base hostname & protocol for your site
twitter_username: ghaz
github_username:  lbradstreet

# Build settings
markdown: kramdown
