# Site settings
title: Lucas Bradstreet
email: blog@lucasbradstreet.com
description: Musings on programming, functional programming, and distributed systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lucasbradstreet.com" # the base hostname & protocol for your site
twitter_username: ghaz
github_username:  lbradstreet

# Build settings
markdown: kramdown
